---
apiVersion: v1
kind: Namespace
metadata:
  name: terratest-rbac-example-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terratest-rbac-example-service-account
  namespace: terratest-rbac-example-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terratest-rbac-example-role
  namespace: terratest-rbac-example-namespace
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terratest-rbac-example-service-account-binding
  namespace: terratest-rbac-example-namespace
subjects:
  - kind: ServiceAccount
    name: terratest-rbac-example-service-account
    namespace: terratest-rbac-example-namespace
roleRef:
  kind: Role
  name: terratest-rbac-example-role
  apiGroup: rbac.authorization.k8s.io
