---
apiVersion: v1
kind: Namespace
metadata:
  name: terratest-ingress-example-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terratest-ingress-example-service-account
  namespace: terratest-ingress-example-namespace
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: terratest-ingress-example-namespace
  name: terratest-ingress-example-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terratest-ingress-example-binding
  namespace: terratest-ingress-example-namespace
subjects:
- kind: ServiceAccount
  name: terratest-ingress-example-service-account
  namespace: terratest-ingress-example-namespace
roleRef:
  kind: Role
  name: terratest-ingress-example-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
   name: terratest-ingress-example-cluster-admin 
subjects:
- kind: ServiceAccount
  name: terratest-ingress-example-service-account
  namespace: terratest-ingress-example-namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io